// PERSONS
export const GET_ALL_PERSONS = 'GET_ALL_PERSONS'
export const PERSIST_CHOSEN_PERSON = 'PERSIST_CHOSEN_PERSON'
export const PERSIST_GROUP = 'PERSIST_GROUP'
export const DELETE_CHOSEN_PERSON = 'DELETE_CHOSEN_PERSON'
export const PERSIST_CHOSEN_PERSON_GROUPS = 'PERSIST_CHOSEN_PERSON_GROUPS'
export const PERSIST_CHOSEN_PERSON_NAMES = 'PERSIST_CHOSEN_PERSON_NAMES'
export const PERSIST_CHOSEN_GROUP = 'PERSIST_CHOSEN_GROUP'
export const PERSIST_CHOSEN_GROUP_MEMBERS = 'PERSIST_CHOSEN_GROUP_MEMBERS'
export const PERSIST_CHOSEN_GROUP_PROCESSES = 'PERSIST_CHOSEN_GROUP_PROCESSES'

export const PERSIST_MEMBERS = 'PERSIST_MEMBERS'
export const FILTER_MEMBERS = 'FILTER_MEMBERS'

export const DELETE_PERSON = 'DELETE_PERSON'